### Get App Token
POST https://v5api.tiltify.com/oauth/token?
    client_id={{TILTIFY_CLIENT_ID}}&
    client_secret={{TILTIFY_SECRET}}&
    grant_type=client_credentials
Accept: application/json
Content-Type: application/json


###
