### user
# curl -X GET 'https://api.twitch.tv/helix/users?id=141981764'
#-H 'Authorization: Bearer cfabdegwdoklmawdzdo98xt2fo512y'
#-H 'Client-Id: uo6dggojyb8d6soh92zknwmi5ej1q2'
GET https://api.twitch.tv/helix/users?login=yogscast
Authorization: Bearer {{TWITCH_ACCESS_TOKEN}}
Client-Id: {{TWITCH_CLIENT_ID}}

### stream
# curl -X GET 'https://api.twitch.tv/helix/users?id=141981764'
#-H 'Authorization: Bearer cfabdegwdoklmawdzdo98xt2fo512y'
#-H 'Client-Id: uo6dggojyb8d6soh92zknwmi5ej1q2'
GET https://api.twitch.tv/helix/streams?user_login=ravs_
Authorization: Bearer {{TWITCH_ACCESS_TOKEN}}
Client-Id: {{TWITCH_CLIENT_ID}}
