### By handle
GET https://youtube.googleapis.com/youtube/v3/channels?part=snippet&forHandle=@hatfilms&key={{YOUTUBE_API_KEY}}
Accept: application/json


### by id
GET https://youtube.googleapis.com/youtube/v3/channels?part=snippet&id=UCH-_hzb2ILSCo9ftVSnrCIQ&key={{YOUTUBE_API_KEY}}
Accept: application/json


### by multiple ids
# curl
#  'https://youtube.googleapis.com/youtube/v3/channels?part=snippet&id=UCs4br3aZLU0sOEM-3n0-6xQ&id=UCH-_hzb2ILSCo9ftVSnrCIQ&key=[YOUR_API_KEY]'
#  --header 'Accept: application/json'
#  --compressed
GET https://youtube.googleapis.com/youtube/v3/channels?part=snippet&id=UCs4br3aZLU0sOEM-3n0-6xQ&
    id=UCH-_hzb2ILSCo9ftVSnrCIQ&key={{YOUTUBE_API_KEY}}
Accept: application/json


### live test id
GET https://www.googleapis.com/youtube/v3/search
    ?part=snippet
    &channelId=UC7A_dLnSAjl7uROCdoNyjzg
    &type=video
    &eventType=live
    &key={{YOUTUBE_API_KEY}}
